### ISSUE TITLE
Broken pipe on every button event

### ISSUE THREAD

**Issue by Glutexo** [encukou/t3#3]
Every button press/release in the emulator window raises a BrokenPipeError:

```
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 234, in 'calling callback function'
  File "/Users/Glutexo/Vývoj/t3/venv/lib/python3.5/site-packages/pyglet/libs/darwin/cocoapy/runtime.py", line 1121, in objc_method
    result = f(py_self, *args)
  File "/Users/Glutexo/Vývoj/t3/venv/lib/python3.5/site-packages/pyglet/window/cocoa/pyglet_view.py", line 151, in pygletKeyDown_
    self._window.dispatch_event('on_key_press', symbol, modifiers)
  File "/Users/Glutexo/Vývoj/t3/venv/lib/python3.5/site-packages/pyglet/window/__init__.py", line 1154, in dispatch_event
    if EventDispatcher.dispatch_event(self, *args) != False:
  File "/Users/Glutexo/Vývoj/t3/venv/lib/python3.5/site-packages/pyglet/event.py", line 355, in dispatch_event
    if handler(*args):
  File "/Users/Glutexo/Vývoj/t3/emu/t3emu.py", line 158, in on_key_press
    in_file.flush()
BrokenPipeError: [Errno 32] Broken pipe
```

Running using Python 3.5.2, Pyglet 1.2.4, Micropython 1.8.4 on macOS Sierra (10.12).

**Comment by encukou** [comment]
This might mean that the MicroPython process crashed. Is there any error before this one?

**Comment by Glutexo** [comment]
This one is raised upon start:

```
Traceback (most recent call last):
  File "main.py", line 169, in <module>
  File "t3.py", line 146, in run
  File "t3.py", line 144, in run
  File "t3.py", line 108, in _sys_task
  File "../emu/neopixel.py", line 20, in write
OSError: 45
```

Appears right after the `* b'92 39 58\n'` lines.

**Comment by Glutexo** [comment]
And this one, right before `* b'# Fork started\n'`:

```
2016-10-11 07:32:28.238 Python[13547:478340] ApplePersistenceIgnoreState: Existing state will not be touched. New state will be written to /var/folders/07/lp6r0md134q3k__b45l9lg1h0000gn/T/org.python.python.savedState
```

**Comment by encukou** [comment]
An internet search suggests 45 is "Operation not supported".
If you comment out `emu/neopixel.py:20` (`sys.stdout.flush()`), does it work?

**Comment by Glutexo** [comment]
Yes. Commenting that out made the emulator work. Thanks!
