### ISSUE TITLE
Game can’t be launched (no method ‹reset›)

### ISSUE THREAD

**Issue by Glutexo** [encukou/t3#4]
This error occurs upon launching any game:

```
Traceback (most recent call last):
  File "main.py", line 22, in <module>
  File "t3.py", line 155, in run
  File "t3.py", line 153, in run
  File "launcher.py", line 103, in main_menu
AttributeError: 'module' object has no attribute 'reset'
```

Happens since updating to the most recent revision.

**Comment by encukou** [comment]
Will investigate. For a workaround, run `./t3 <name>` (e.g. `./t3 repeat`).

**Comment by Glutexo** [comment]
Doesn’t happen to me any more. Don’t know why.
